### ISSUE TITLE
Syntax for fetching FimaNfipPolicies policies by year

### ISSUE THREAD

**Issue by Steve-Koller** [dylan-turner25/rfema#16]
Hi, thanks for the package! I'm trying to fetch NFIP policies data by year, since importing the whole .csv file and fetching the entire bulk file via the API isn't doable locally on my machine. In package documentation, `yearOfLoss` is used as an example for the `FimaNfipClaims` dataset. Unfortunately, `FimaNfipPolicies` doesn't have a year variable that is so easily filtered.

 For example, I'm using syntax like the below to try to import all policies that have a policy effective date that began in 2020. I'm getting 

**Attempt 1**
```
data_2020 <- open_fema("FimaNfipPolicies", 
   filters = startswith(policyEffectiveDate, "2020"))
```
This produces the following error: `Error in startswith(policyEffectiveDate, "2020") : could not find function "startswith"`.

**Attempt 2**
```
data_2020 <- open_fema("FimaNfipPolicies", filters = "substring(policyEffectiveDate, 1, 4) == '2020'")
```
The second attempt produces `Error in (function (data_set, top_n = NULL, filters = NULL, select = NULL,  : Client error: (400) Bad Request`

Do you have any advice on how to cleanly apply a "year" filter at point of API fetch for this particular dataset? Thank you!

**Comment by dylan-turner25** [comment]
Hi Steve, you can do something like this to filter date objects. 

`filter_list <-  list(policyEffectiveDate = ">= 2020-01-01", policyEffectiveDate = "<= 2020-01-31")`

`data <- open_fema("fimanfippolicies", filters = filter_list)`

This will return all observations with effective policy dates that are in January of 2020. In general, you can't use functions you would normally use in R (like `startswith()`)  to construct filters as the API doesn't "understand" these.

**Comment by Steve-Koller** [comment]
Awesome, works like a charm. Thank you, Dylan!
